### ISSUE TITLE
全自动模式，巴林达任务9

### ISSUE THREAD

**Issue by z-henry** [jimowushuang/hs-mercenary#11]
巴林达任务9是队伍使用冰霜法术造成伤害
![QQ图片20220617092758](https://user-images.githubusercontent.com/40875274/174204276-a2399d7b-cad3-49a4-aa4e-abe330860ced.png)

但是全自动做任务，巴林达不会释放冰霜技能（2技能）而是火焰技能（1技能），而队伍也没有能施放的，这个任务就会卡住
![QQ图片20220617092748](https://user-images.githubusercontent.com/40875274/174204399-dfcc3adf-ba6d-4449-8c67-6ebb7fd30330.png)

**Comment by jimowushuang** [comment]
ok。晚一点我处理一下

**Comment by z-henry** [comment]
谢谢，邮件已收到！

**Comment by z-henry** [comment]
另外发现任务10是杀元素，貌似全自动模式还在刷2-5，可否考虑调到h1-2做任务

**Comment by jimowushuang** [comment]
> 另外发现任务10是杀元素，貌似全自动模式还在刷2-5，可否考虑调到h1-2做任务

可以

**Comment by z-henry** [comment]
玛法里奥·怒风——任务3：自然力量——0 / 85使用大德鲁伊的召唤造成85点伤害。
这里虽然可以使用3技能，但是抉择的时候会选择回血而不是打伤害。

不好意思哈，反馈的有些频繁。

**Comment by jimowushuang** [comment]
> 玛法里奥·怒风——任务3：自然力量——0 / 85使用大德鲁伊的召唤造成85点伤害。 这里虽然可以使用3技能，但是抉择的时候会选择回血而不是打伤害。
> 
> 不好意思哈，反馈的有些频繁。

嗯，这个问题是已知问题，海军上尉有一个任务也是这样的。这个涉及到底层改动，会修复的优先级会稍微低一点。

**Comment by jimowushuang** [comment]
除了回复那个其他的都处理了 回复那个我新开了 issue https://github.com/jimowushuang/hs-mercenary/issues/14 这个先关掉了
