### ISSUE TITLE
策略建议

### ISSUE THREAD

**Issue by xiamh3** [jimowushuang/hs-mercenary#12]
卡扎库斯优先技能可以设为召唤嘲讽魔像
刷图时可以优先集火对面的雷矛防御者

**Comment by jimowushuang** [comment]
详细说一下场景，这两个建议并不是通用的

**Comment by xiamh3** [comment]
卡扎库斯可以考虑默认技能召唤嘲讽魔像，现在卡扎是默认使用一技能不太好配合恩佐斯；
对面的雷矛防御者第二回合会使用一个强化队友的技能，队友受到伤害会给雷矛防御者增加属性，很容易让雷矛防御70/150+

**Comment by jimowushuang** [comment]
支持了自定义策略，可以参考一下 https://github.com/jimowushuang/hs-mercenary-strategy
