### ISSUE TITLE
希望能加入PVP模式，哪怕是最简单的组合都行

### ISSUE THREAD

**Issue by tianganyan** [jimowushuang/hs-mercenary#15]
希望能加入PVP模式，哪怕是最简单的组合都行

**Comment by jimowushuang** [comment]
可以考虑 现在正在做策略，做完了可以加一下

**Comment by jimowushuang** [comment]
支持pvp了，但是目前没有策略，自定义策略可以参考 https://github.com/jimowushuang/hs-mercenary-strategy 原则上我不会参与策略的开发
