### ISSUE TITLE
怎么把策略加入刀插件里面，我放在plugins文件夹下面，但是还是在插件里面不显示，具体如下图显示

### ISSUE THREAD

**Issue by tianganyan** [jimowushuang/hs-mercenary#19]
![GIB~P4{9YH4$E(A52$D4`ME](https://user-images.githubusercontent.com/107686764/174435504-50442360-2ea5-4321-b382-16a26fb0dd0a.png)
![L4DKI}DT81~I A}$31)T0SD](https://user-images.githubusercontent.com/107686764/174435506-3d87a2d9-a9bf-4075-8a7d-12f46679d371.png)

**Comment by jimowushuang** [comment]
要按照 https://github.com/jimowushuang/hs-mercenary-strategy 这个格式来。 你的那些策略是哪来的？

**Comment by tianganyan** [comment]
我要不要把这些策略都发出来给你
