### ISSUE TITLE
有些阴间任务,希望弄个某些佣兵组合自动完成

### ISSUE THREAD

**Issue by Andy-tanbin** [jimowushuang/hs-mercenary#8]
![image](https://user-images.githubusercontent.com/13927098/173985446-bfca3f31-16cc-4cd8-949c-a2f7c293bad7.png)
晨拥的任务是真的阴间~  打龙能不能去黑石山屠龙:stuck_out_tongue:

**Comment by jimowushuang** [comment]
OK，这些逻辑我看一下加一下
